version: "3"
services:
  sush1-bot:
    platform: linux/amd64
    image: "sush1-bot:0.1.0"
    container_name: "sush1-bot"
    build:
      context: ./bot
      dockerfile: Dockerfile
    volumes:
      - ./bot:/usr/src/bot:cached
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: sush1
      POSTGRES_PASSWORD: posgre
      POSTGRES_DB: sush1-bot-db
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      TZ: "Asia/Tokyo"
    ports:
      - 5432:5432
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
      - sush1-bot-db:/var/lib/postgresql/data

volumes:
  sush1-bot-db:
